### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bomb20** [tatthien/giraffe#1]
Hi,

I kind of had the same Idea about starting 2022 with static-site-generation in go for a small personal website thingy.
Since I'd like to use giraffe as a base to start from (and of cause contribute things back to) I wanted to ask, how you plan on licensing your code.

**Comment by tatthien** [comment]
Hi @bomb20 

License added https://github.com/tatthien/giraffe/blob/master/LICENSE

I appreciate your contributions.

**Comment by tatthien** [comment]
Closing this issue due to no longer responding.
